
####PLUGIN TO SET STATE DROPPED#######
com.lcs.wc.foundation.LCSPluginManager.eventPlugin.1001=targetClass|com.lcs.wc.season.LCSSeasonProductLink^targetType|ALL^pluginClass|com.cabelas.wc.product.CabProductPlugins^pluginMethod|setProductLifecycleState^event|POST_PERSIST^priority|1
#######PLUGIN TO SET USERLIST##########
com.lcs.wc.foundation.LCSPluginManager.eventPlugin.1002=targetClass|com.lcs.wc.product.LCSProduct^targetType|ALL^pluginClass|com.cabelas.wc.product.CabProductPlugins^pluginMethod|setUserListToRoles^event|POST_UPDATE_PERSIST^priority|1
com.lcs.wc.foundation.LCSPluginManager.eventPlugin.1003=targetClass|com.lcs.wc.season.LCSSeasonProductLink^targetType|ALL^pluginClass|com.cabelas.wc.product.CabProductPlugins^pluginMethod|setUserListToRoles^event|PRE_CREATE_PERSIST^priority|1

