FIND_MATERIAL_FORECAST_REPORT=MATERIAL_FORECAST_REPORT_CONTROLLER
GENERATE_MUR_FORECAST_REPORT=MATERIAL_FORECAST_REPORT_CONTROLLER
LOAD_PLANDATA_FROM_EXCEL=PLAN_LOAD_CSV_CONTROLLER
VIEW_SEASON_PRODUCTION_PLANNING=PLAN_LOAD_CSV_CONTROLLER
VIEW_SEASON_PLANNING=PLAN_LOAD_CSV_CONTROLLER

#####DOCUMENT SUMMARY CONTROLLER - DOCUMENT DASHBOARD-CPS#####
DOCUMENT_SUMMARY=DOCUMENT_SUMMARY_CONTROLLER
###############################################################