##########################################################################
#
# File: custom.clientSidePluginManagerMappings.properties
#
# Use this file is used to map specific specific Client Side Plugin JSPs    
# to the generation of specific Flextype pages. 
# User customizations should be made to this file by a User, Administrator, 
#  Developer etc. 
# 
# The format is <FlextypePath>.<activity>.<action>.<clientSidePluginType>=<file Path>
# <FlextypePath> = RootType.Subtype.Subtype etc.        (Remove the spaces from the Type name) 
#                  Document.StandardsDocuments.ISO9000  (where the Type Name was 'Standards Documents')
# <activity> = CREATE_DOCUMENT
# <action>   = CLASSIFY
# <clientSidePluginType> = handleWidgetEvent, handleSubmitEvent, or onLoadEvent
# The entry would appear as follows:
#   Document.StandardsDocuments.ISO9000.CREATE_DOCUMENT.CLASSIFY.handleWidgetEvent=/Company/jsp/document/widgetPlugin_CSP.jsp
############################################################################

## Example settings for the Document FlexType
##Document.StandardsDocuments.ISO9000.CREATE_DOCUMENT.CLASSIFY.handleWidgetEvent=/MyCompany/jsp/document/widgetDocumentStdIso9000_CSP.jsp
##Document.StandardsDocuments.ISO9000.CREATE_DOCUMENT.CLASSIFY.handleSubmitEvent=/MyCompany/jsp/document/submitDocumentStdIso9000_CSP.jsp
##Document.StandardsDocuments.ISO9000.CREATE_DOCUMENT.CLASSIFY.onLoadEvent=/MyCompany/jsp/document/onLoadDocumentStdIso9000_CSP.jsp
##

######################TESTING SAMPLE-DEFAULT REQUESTOR-CPS######################################################
Sample.Product.TestingRequest.CREATE_TESTING_REQUEST.CLASSIFY.onLoadEvent = /cabelas/jsp/samples/CPSRequestedByTestingSample_OnLoad.jsp
Sample.Material.TestingRequest.CREATE_TESTING_REQUEST.CLASSIFY.onLoadEvent = /cabelas/jsp/samples/CPSRequestedByTestingSample_OnLoad.jsp
############################################################################################################